#pragma once

/* vvv CUSTOMIZE YOUR CONFIG HERE vvv */
#define LAUNCH_EVERYTHING
#define LAUNCH_NO_THREAD_SAFE
/* ^^^ CUSTOMIZE YOUR CONFIG HERE ^^^ */

#if defined(LAUNCH_EVERYTHING)
#define LAUNCH_FMTIO_NULLSTREAM
#define LAUNCH_EXPERIMENTAL
#endif